favicon: null
name: Surfwagen
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.387982222950086
  brandStrength: 0.6690432180184871
  rhythmicContrast: 0.3647800362668931
  brandColors:
    - '#ffa251'
    - '#263226'
    - '#425574'
    - '#d2d3d9'
    - '#f1f3fc'
  lightness: 0.9676337204873562
typography_spectrum: 0.8467340040951967
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
